[class]
audio_default	= [
	{ command = "mpv", args = [ "--" ] },
	{ command = "mediainfo", confirm_exit = true },
]

image_default	= [
	{ command = "ristretto", fork = true, silent = true },
]

video_default	= [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
	{ command = "mpv", args = [ "--mute", "on", "--" ], fork = true, silent = true },
]


text_default	= [
    { command = "vim" },
    { command = "bat", args = [ "--paging=always" ] },
]

reader_default	= [
	{ command = "zathura", fork = true, silent = true },
]

libreoffice_default	= [
	{ command = "libreoffice", fork = true, silent = true },
]

[extension]
# inherit from image_default class
png.inherit = "image_default"

# inherit from image_default class
jpg.inherit = "image_default"
# in addition, also add gimp for .jpg files only

mkv.app_list    = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
	{ command = "mpv", args = [ "--mute", "on", "--" ], fork = true, silent = true } 
]

rs.app_list = [
        { command = "bat", confirm_exit = true } 
]

## audio formats
flac.inherit	= "audio_default"
m4a.inherit	= "audio_default"
mp3.inherit	= "audio_default"
ogg.inherit	= "audio_default"
wav.inherit	= "audio_default"

## video formats
avi.inherit	= "video_default"
av1.inherit	= "video_default"
flv.inherit	= "video_default"
mkv.inherit	= "video_default"
m4v.inherit	= "video_default"
mov.inherit	= "video_default"
mp4.inherit	= "video_default"
ts.inherit	= "video_default"
webm.inherit	= "video_default"
wmv.inherit	= "video_default"


## text formats
build.inherit	= "text_default"
c.inherit   = "text_default"
cmake.inherit	= "text_default"
conf.inherit	= "text_default"
cpp.inherit = "text_default"
css.inherit = "text_default"
csv.inherit = "text_default"
cu.inherit  = "text_default"
dart.inherit	= "text_default"
ebuild.inherit	= "text_default"
eex.inherit = "text_default"
env.inherit = "text_default"
ex.inherit  = "text_default"
exs.inherit = "text_default"
go.inherit  = "text_default"
h.inherit   = "text_default"
hpp.inherit = "text_default"
hs.inherit  = "text_default"
html.inherit	= "text_default"
ini.inherit = "text_default"
java.inherit	= "text_default"
js.inherit  = "text_default"
json.inherit	= "text_default"
kt.inherit  = "text_default"
lua.inherit = "text_default"
log.inherit = "text_default"
md.inherit  = "text_default"
micro.inherit	= "text_default"
ninja.inherit	= "text_default"
py.inherit  = "text_default"
rkt.inherit = "text_default"
rs.inherit  = "text_default"
scss.inherit	= "text_default"
sh.inherit  = "text_default"
srt.inherit = "text_default"
svelte.inherit	= "text_default"
toml.inherit	= "text_default"
tsx.inherit = "text_default"
txt.inherit = "text_default"
vim.inherit = "text_default"
xml.inherit = "text_default"
yaml.inherit	= "text_default"
yml.inherit = "text_default"

# pdf 
pdf.inherit = "reader_default"

# Office
odt.inherit	= "libreoffice_default"
odf.inherit	= "libreoffice_default"
ods.inherit	= "libreoffice_default"
odp.inherit	= "libreoffice_default"

doc.inherit	= "libreoffice_default"
docx.inherit	= "libreoffice_default"
xls.inherit	= "libreoffice_default"
xlsx.inherit	= "libreoffice_default"
ppt.inherit	= "libreoffice_default"
pptx.inherit	= "libreoffice_default"

[mimetype]

# text/*
[mimetype.text]
inherit = "text_default"

# application/octet-stream
[mimetype.application.subtype.octet-stream]
inherit = "video_default"
